// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryDeploy) DeepCopyInto(out *CanaryDeploy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryDeploy.
func (in *CanaryDeploy) DeepCopy() *CanaryDeploy {
	if in == nil {
		return nil
	}
	out := new(CanaryDeploy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CanaryDeploy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryDeployList) DeepCopyInto(out *CanaryDeployList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CanaryDeploy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryDeployList.
func (in *CanaryDeployList) DeepCopy() *CanaryDeployList {
	if in == nil {
		return nil
	}
	out := new(CanaryDeployList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CanaryDeployList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryDeploySpec) DeepCopyInto(out *CanaryDeploySpec) {
	*out = *in
	out.DeployRef = in.DeployRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryDeploySpec.
func (in *CanaryDeploySpec) DeepCopy() *CanaryDeploySpec {
	if in == nil {
		return nil
	}
	out := new(CanaryDeploySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryDeployStatus) DeepCopyInto(out *CanaryDeployStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryDeployStatus.
func (in *CanaryDeployStatus) DeepCopy() *CanaryDeployStatus {
	if in == nil {
		return nil
	}
	out := new(CanaryDeployStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployReference) DeepCopyInto(out *DeployReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployReference.
func (in *DeployReference) DeepCopy() *DeployReference {
	if in == nil {
		return nil
	}
	out := new(DeployReference)
	in.DeepCopyInto(out)
	return out
}
