// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1beta1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/canary/v1beta1.CanaryDeploy":       schema_pkg_apis_canary_v1beta1_CanaryDeploy(ref),
		"./pkg/apis/canary/v1beta1.CanaryDeploySpec":   schema_pkg_apis_canary_v1beta1_CanaryDeploySpec(ref),
		"./pkg/apis/canary/v1beta1.CanaryDeployStatus": schema_pkg_apis_canary_v1beta1_CanaryDeployStatus(ref),
	}
}

func schema_pkg_apis_canary_v1beta1_CanaryDeploy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CanaryDeploy is the Schema for the canarydeploys API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/canary/v1beta1.CanaryDeploySpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/canary/v1beta1.CanaryDeployStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/canary/v1beta1.CanaryDeploySpec", "./pkg/apis/canary/v1beta1.CanaryDeployStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_canary_v1beta1_CanaryDeploySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CanaryDeploySpec defines the desired state of CanaryDeploy",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_canary_v1beta1_CanaryDeployStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "CanaryDeployStatus defines the observed state of CanaryDeploy",
				Type:        []string{"object"},
			},
		},
	}
}
